In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
arr[::-1]

array([5, 4, 3, 2, 1])

In [15]:
two_d_arr = np.array([[5, 3, 1], [10, 20, 7], [30, 70, 50]])

In [16]:
two_d_arr[1,2]

np.int64(7)

In [17]:
two_d_arr.sort()

In [18]:
two_d_arr

array([[ 1,  3,  5],
       [ 7, 10, 20],
       [30, 50, 70]])